// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _2proj2.Models;

namespace _2proj2.Migrations
{
    [DbContext(typeof(TimeFormContext))]
    partial class TimeFormContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("_2proj2.Models.User", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("End")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GroupSize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Start")
                        .HasColumnType("TEXT");

                    b.HasKey("GroupId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            GroupId = 1,
                            Email = "",
                            End = new DateTime(2022, 4, 1, 8, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 1, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 2,
                            Email = "",
                            End = new DateTime(2022, 4, 1, 9, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 1, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 3,
                            Email = "",
                            End = new DateTime(2022, 4, 1, 10, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 1, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 4,
                            Email = "",
                            End = new DateTime(2022, 4, 1, 11, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 1, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 5,
                            Email = "",
                            End = new DateTime(2022, 4, 1, 12, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 1, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 6,
                            Email = "",
                            End = new DateTime(2022, 4, 1, 13, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 1, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 7,
                            Email = "",
                            End = new DateTime(2022, 4, 1, 14, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 1, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 8,
                            Email = "",
                            End = new DateTime(2022, 4, 1, 15, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 1, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 9,
                            Email = "",
                            End = new DateTime(2022, 4, 1, 16, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 1, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 10,
                            Email = "",
                            End = new DateTime(2022, 4, 1, 17, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 1, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 11,
                            Email = "",
                            End = new DateTime(2022, 4, 1, 18, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 1, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 12,
                            Email = "",
                            End = new DateTime(2022, 4, 1, 19, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 1, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 13,
                            Email = "",
                            End = new DateTime(2022, 4, 1, 20, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 1, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 14,
                            Email = "",
                            End = new DateTime(2022, 4, 2, 8, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 2, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 15,
                            Email = "",
                            End = new DateTime(2022, 4, 2, 9, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 2, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 16,
                            Email = "",
                            End = new DateTime(2022, 4, 2, 10, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 2, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 17,
                            Email = "",
                            End = new DateTime(2022, 4, 2, 11, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 2, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 18,
                            Email = "",
                            End = new DateTime(2022, 4, 2, 12, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 2, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 19,
                            Email = "",
                            End = new DateTime(2022, 4, 2, 13, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 2, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 20,
                            Email = "",
                            End = new DateTime(2022, 4, 2, 14, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 2, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 21,
                            Email = "",
                            End = new DateTime(2022, 4, 2, 15, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 2, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 22,
                            Email = "",
                            End = new DateTime(2022, 4, 2, 16, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 2, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 23,
                            Email = "",
                            End = new DateTime(2022, 4, 2, 17, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 2, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 24,
                            Email = "",
                            End = new DateTime(2022, 4, 2, 18, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 2, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 25,
                            Email = "",
                            End = new DateTime(2022, 4, 2, 19, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 2, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 26,
                            Email = "",
                            End = new DateTime(2022, 4, 2, 20, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 2, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 27,
                            Email = "",
                            End = new DateTime(2022, 4, 3, 8, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 3, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 28,
                            Email = "",
                            End = new DateTime(2022, 4, 3, 9, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 3, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 29,
                            Email = "",
                            End = new DateTime(2022, 4, 3, 10, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 3, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 30,
                            Email = "",
                            End = new DateTime(2022, 4, 3, 11, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 3, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 31,
                            Email = "",
                            End = new DateTime(2022, 4, 3, 12, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 3, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 32,
                            Email = "",
                            End = new DateTime(2022, 4, 3, 13, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 3, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 33,
                            Email = "",
                            End = new DateTime(2022, 4, 3, 14, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 3, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 34,
                            Email = "",
                            End = new DateTime(2022, 4, 3, 15, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 3, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 35,
                            Email = "",
                            End = new DateTime(2022, 4, 3, 16, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 3, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 36,
                            Email = "",
                            End = new DateTime(2022, 4, 3, 17, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 3, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 37,
                            Email = "",
                            End = new DateTime(2022, 4, 3, 18, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 3, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 38,
                            Email = "",
                            End = new DateTime(2022, 4, 3, 19, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 3, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 39,
                            Email = "",
                            End = new DateTime(2022, 4, 3, 20, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 3, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 40,
                            Email = "",
                            End = new DateTime(2022, 4, 4, 8, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 4, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 41,
                            Email = "",
                            End = new DateTime(2022, 4, 4, 9, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 4, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 42,
                            Email = "",
                            End = new DateTime(2022, 4, 4, 10, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 4, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 43,
                            Email = "",
                            End = new DateTime(2022, 4, 4, 11, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 4, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 44,
                            Email = "",
                            End = new DateTime(2022, 4, 4, 12, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 4, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 45,
                            Email = "",
                            End = new DateTime(2022, 4, 4, 13, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 4, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 46,
                            Email = "",
                            End = new DateTime(2022, 4, 4, 14, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 4, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 47,
                            Email = "",
                            End = new DateTime(2022, 4, 4, 15, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 4, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 48,
                            Email = "",
                            End = new DateTime(2022, 4, 4, 16, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 4, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 49,
                            Email = "",
                            End = new DateTime(2022, 4, 4, 17, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 4, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 50,
                            Email = "",
                            End = new DateTime(2022, 4, 4, 18, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 4, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 51,
                            Email = "",
                            End = new DateTime(2022, 4, 4, 19, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 4, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 52,
                            Email = "",
                            End = new DateTime(2022, 4, 4, 20, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 4, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 53,
                            Email = "",
                            End = new DateTime(2022, 4, 5, 8, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 5, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 54,
                            Email = "",
                            End = new DateTime(2022, 4, 5, 9, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 5, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 55,
                            Email = "",
                            End = new DateTime(2022, 4, 5, 10, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 5, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 56,
                            Email = "",
                            End = new DateTime(2022, 4, 5, 11, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 5, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 57,
                            Email = "",
                            End = new DateTime(2022, 4, 5, 12, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 5, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 58,
                            Email = "",
                            End = new DateTime(2022, 4, 5, 13, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 5, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 59,
                            Email = "",
                            End = new DateTime(2022, 4, 5, 14, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 5, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 60,
                            Email = "",
                            End = new DateTime(2022, 4, 5, 15, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 5, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 61,
                            Email = "",
                            End = new DateTime(2022, 4, 5, 16, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 5, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 62,
                            Email = "",
                            End = new DateTime(2022, 4, 5, 17, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 5, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 63,
                            Email = "",
                            End = new DateTime(2022, 4, 5, 18, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 5, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 64,
                            Email = "",
                            End = new DateTime(2022, 4, 5, 19, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 5, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 65,
                            Email = "",
                            End = new DateTime(2022, 4, 5, 20, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 5, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 66,
                            Email = "",
                            End = new DateTime(2022, 4, 6, 8, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 6, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 67,
                            Email = "",
                            End = new DateTime(2022, 4, 6, 9, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 6, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 68,
                            Email = "",
                            End = new DateTime(2022, 4, 6, 10, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 6, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 69,
                            Email = "",
                            End = new DateTime(2022, 4, 6, 11, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 6, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 70,
                            Email = "",
                            End = new DateTime(2022, 4, 6, 12, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 6, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 71,
                            Email = "",
                            End = new DateTime(2022, 4, 6, 13, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 6, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 72,
                            Email = "",
                            End = new DateTime(2022, 4, 6, 14, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 6, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 73,
                            Email = "",
                            End = new DateTime(2022, 4, 6, 15, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 6, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 74,
                            Email = "",
                            End = new DateTime(2022, 4, 6, 16, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 6, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 75,
                            Email = "",
                            End = new DateTime(2022, 4, 6, 17, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 6, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 76,
                            Email = "",
                            End = new DateTime(2022, 4, 6, 18, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 6, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 77,
                            Email = "",
                            End = new DateTime(2022, 4, 6, 19, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 6, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 78,
                            Email = "",
                            End = new DateTime(2022, 4, 6, 20, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 6, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 79,
                            Email = "",
                            End = new DateTime(2022, 4, 7, 8, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 7, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 80,
                            Email = "",
                            End = new DateTime(2022, 4, 7, 9, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 7, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 81,
                            Email = "",
                            End = new DateTime(2022, 4, 7, 10, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 7, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 82,
                            Email = "",
                            End = new DateTime(2022, 4, 7, 11, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 7, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 83,
                            Email = "",
                            End = new DateTime(2022, 4, 7, 12, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 7, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 84,
                            Email = "",
                            End = new DateTime(2022, 4, 7, 13, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 7, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 85,
                            Email = "",
                            End = new DateTime(2022, 4, 7, 14, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 7, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 86,
                            Email = "",
                            End = new DateTime(2022, 4, 7, 15, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 7, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 87,
                            Email = "",
                            End = new DateTime(2022, 4, 7, 16, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 7, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 88,
                            Email = "",
                            End = new DateTime(2022, 4, 7, 17, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 7, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 89,
                            Email = "",
                            End = new DateTime(2022, 4, 7, 18, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 7, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 90,
                            Email = "",
                            End = new DateTime(2022, 4, 7, 19, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 7, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroupId = 91,
                            Email = "",
                            End = new DateTime(2022, 4, 7, 20, 59, 59, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Name = "",
                            Phone = "",
                            Start = new DateTime(2022, 4, 7, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
